let bundeslaender = [ 
    {
        "name": "Baden-Württemberg",
        "population": 11.1,
        "url": "https://www.baden-wuerttemberg.de/de/startseite/",
        "comments": [],
        "weinkonsum": 26.5, 
        "bevoelkerungsdichte": 308,
        "area": 35748,
        "raucher": 21.3,
        "wolves": 42,
        "dogs": 1.01,
        "suicide": 10.6,
        "kids": 1.59,
        "cats": 0.89,
        "imagefile": "bw"
    },
    {
        "name": "Bayern",
        "population": 13.1,
        "url": "https://www.bayern.de/",
        "comments": ['Tolles Wetter und gute Wander-Routen', 'München ist eine schöne Stadt'],
        "weinkonsum": 22.1, 
        "bevoelkerungsdichte": 184,
        "area": 70542,
        "raucher": 20.5,
        "wolves": 63,
        "dogs": 1.51,
        "suicide": 11.4,
        "kids": 1.56,
        "cats": 1.22,
        "imagefile": "b"



    },
    {
        "name": "Berlin",
        "population": 3.7,
        "url": "https://www.berlin.de/",
        "comments": [],
        "weinkonsum": 21.3, 
        "bevoelkerungsdichte": 4055,
        "area": 891,
        "raucher": 25.5,
        "wolves": 0,
        "dogs": 0.39,
        "suicide": 11.1,
        "kids": 1.54,
        "cats": 0.38
   
    },
    {
        "name": "Brandenburg",
        "population": 2.5,
        "url": "https://www.brandenburg.de/",
        "comments": [],
        "weinkonsum": 20.9, 
        "bevoelkerungsdichte": 84,
        "area": 29654,
        "raucher": 24.5,
        "wolves": 1173,
        "dogs": 0.52,
        "suicide": 10.0,
        "kids": 1.69,
        "cats": 0.38,
        "imagefile": "br"
     
    },
    {
        "name": "Bremen",
        "population": 0.7,
        "url": "https://www.bremen.de/",
        "comments": ['Die Stadtmusikanten haben mir schon immer gefallen!'],
        "weinkonsum": 20.7, 
        "bevoelkerungsdichte": 1624,
        "area": 420,
        "raucher": 27.4,
        "wolves": 0,
        "dogs": 0.06,
        "suicide": 10.9,
        "kids": 1.63,
        "cats": 0.06
    },
    {
        "name": "Hamburg",
        "population": 1.8,
        "url": "https://www.hamburg.de/",
        "comments": ['Ein wirklich tolles Bundesland'],
        "weinkonsum": 20.7, 
        "bevoelkerungsdichte": 2424,
        "area": 755,
        "raucher": 23.2,
        "wolves": 0,
        "dogs": 0.2,
        "suicide": 11.7,
        "kids": 1.55,
        "cats": 0.15
    },
    {
        "name": "Hessen",
        "population": 6.3,
        "url": "https://www.hessen.de/",
        "comments": [],
        "weinkonsum": 18.5, 
        "bevoelkerungsdichte": 296,
        "area": 21116,
        "raucher": 21.1,
        "wolves": 16,
        "dogs": 0.73,
        "suicide": 12,
        "kids": 1.58,
        "cats": 0.43
    },
    {
        "name": "Mecklenburg-Vorpommern",
        "population": 1.6,
        "url": "https://www.mecklenburg-vorpommern.de/startseite/",
        "comments": [],
        "weinkonsum": 20.9, 
        "bevoelkerungsdichte": 69,
        "area": 23295,
        "raucher": 27.7,
        "wolves": 244,
        "dogs": 0.22,
        "suicide": 12.1,
        "kids": 1.56,
        "cats": 0.17,
        "imagefile": "mv"
    },
    {
        "name": "Niedersachsen",
        "population": 8,
        "url": "https://www.niedersachsen.de/startseite/",
        "comments": [],
        "weinkonsum": 20.7, 
        "bevoelkerungsdichte": 167,
        "area": 47710,
        "raucher": 22.9,
        "wolves": 842,
        "dogs": 0.92,
        "suicide": 10.8,
        "kids": 1.68,
        "cats": 0.85
    },
    {
        "name": "Nordrhein-Westfalen",
        "population": 17.9,
        "url": "https://www.land.nrw/",
        "comments": [],
        "weinkonsum": 18, 
        "bevoelkerungsdichte": 525,
        "area": 34112,
        "raucher": 22.6,
        "wolves": 119,
        "dogs": 2.5,
        "suicide": 7.4,
        "kids": 1.61,
        "cats": 1.36,
        "imagefile": "nrw"
    
    },
    {
        "name": "Rheinland-Pfalz",
        "population": 4.1,
        "url": "https://www.rlp.de/de/startseite/",
        "comments": [],
        "weinkonsum": 18.5, 
        "bevoelkerungsdichte": 205,
        "area": 19858,
        "raucher": 21.7,
        "wolves": 101,
        "dogs": 0.54,
        "suicide": 11.1,
        "kids": 1.60,
        "cats": 0.44
    
    },
    {
        "name": "Saarland",
        "population": 1,
        "url": "https://www.saarland.de/DE/home/home_node.html",
        "comments": [],
        "weinkonsum": 18.5, 
        "bevoelkerungsdichte": 387,
        "area": 2571,
        "raucher": 20.6,
        "wolves": 0,
        "dogs": 0.15,
        "suicide": 8.4,
        "kids": 1.49,
        "cats": 0.09,
      
    },
    {
        "name": "Sachsen",
        "population": 4.1,
        "url": "https://www.sachsen.de/",
        "comments": [],
        "weinkonsum": 21.2, 
        "bevoelkerungsdichte": 221,
        "area": 18450,
        "raucher": 21.5,
        "wolves": 435,
        "dogs": 0.44,
        "suicide": 14,
        "kids": 1.66,
        "cats": 0.39,
        "imagefile": "s"
    },
    {
        "name": "Sachsen-Anhalt",
        "population": 2.2,
        "url": "https://www.sachsen-anhalt.de/startseite/",
        "comments": [],
        "weinkonsum": 20.9, 
        "bevoelkerungsdichte": 109,
        "area": 20459,
        "raucher": 24.7,
        "wolves": 283,
        "dogs": 0.34,
        "suicide": 13.9,
        "kids": 1.62,
        "cats": 0.23
       
    },
    {
        "name": "Schleswig-Holstein",
        "population": 2.9,
        "url": "https://www.schleswig-holstein.de/DE/Home/home_node.html",
        "comments": [],
        "weinkonsum": 20.7, 
        "bevoelkerungsdichte": 183,
        "area": 15804,
        "raucher": 23.5,
        "wolves": 46,
        "dogs": 0.4,
        "suicide": 12.1,
        "kids": 1.61,
        "cats": 0.21
    
    },
    {
        "name": "Thüringen",
        "population": 2.1,
        "url": "https://thueringen.de/",
        "comments": [],
        "weinkonsum": 21.2, 
        "bevoelkerungsdichte": 232,
        "area": 16202,
        "raucher": 26.2,
        "wolves": 10,
        "dogs": 0.26,
        "suicide": 13.6,
        "kids": 1.63,
        "cats": 0.26
        
    }
];